version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/leowilbur/task_manager

    steps:
      - checkout
      - run:
          name: Run the linter
          command: go test -v ./...